
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2015-05-19 11:36:06.525986
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
x86_64_cel_redstone_xp_BASEDIR := $(BASEDIR)x86_64_cel_redstone_xp


ALL_MODULES := $(ALL_MODULES) x86_64_cel_redstone_xp
