
###############################################################################
#
# Inclusive Makefile for the x86_64_cel_redstone_xp module.
#
# Autogenerated 2015-05-19 11:36:06.472773
#
###############################################################################
x86_64_cel_redstone_xp_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_cel_redstone_xp_BASEDIR)/module/make.mk
include $(x86_64_cel_redstone_xp_BASEDIR)/module/auto/make.mk
include $(x86_64_cel_redstone_xp_BASEDIR)/module/src/make.mk
include $(x86_64_cel_redstone_xp_BASEDIR)/utest/_make.mk

